import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

import {ThemeProvider} from '@/providers/theme-provider'   //dark mode wrappin

const DM_San = DM_Sans({
  subsets: ["latin"],               //Make changes here to change the font
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={DM_San.className}            //font family
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem                              //wrap the dark mode snippet with children inside it. 
            disableTransitionOnChange  
          >
            {children}
          </ThemeProvider>
        
      </body>
    </html>
  )
}





